. ~/.bash_colors
. ~/.bash_aliases

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

if [ -n "$SSH_CLIENT" ]; then
	PS1="[\[$Red\]SSH:\h\[$Color_Off\]:\[$Yellow\]\W\[$Color_Off\]] "
else
	PS1="[\[$Red\]\h\[$Color_Off\]:\[$Yellow\]\W\[$Color_Off\]] "
fi

export PATH="$HOME/bin:$HOME/opt/bin:/usr/local/bin:$PATH"
export LD_LIBRARY_PATH="$HOME/opt/lib:$LD_LIBRARY_PATH:/usr/local/lib"
export MANPATH="$HOME/opt/man:$MANPATH:/usr/local/man"
export PKG_CONFIG_PATH="$HOME/opt/lib/pkgconfig:$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig"

# export BROWSER=firefox
export EDITOR=emacs
export VISUAL=$EDITOR
# export COLORTERM=yes
# export SHELL=/bin/bash
# export MOZ_GLX_IGNORE_BLACKLIST=1
# export MOZ_DISABLE_PANGO=1
# export GDK_USE_XFT=0
# export QT_XFT=false
export HISTCONTROL=ignoreboth

# alias pac="pacman"
# alias pinstall="yaourt -S"
# alias premove="yaourt -Rcsn"
# alias pupgrade="yaourt -Syu"

alias ls="ls -lh --color=auto --group-directories-first"
# alias ll="ls -l"
# alias la="ls -a"
alias lla="ls -la"
alias grep="grep --color=auto"

# web aliases
# alias -s org=$BROWSER
# alias -s com=$BROWSER
# alias -s net=$BROWSER
# alias -s c=$EDITOR
# alias -s h=$EDITOR
