#!/bin/sh

# Load dbus for the X11 session
dbus_file="/etc/X11/xinit/xinitrc.d/30-dbus"
[ -x "$f" ] && . "$f"

# Set the env-var for the Gtk theme (Skype and Qt apps)
export GTK2_RC_FILES="$HOME/.gtkrc-2.0.mine"

# Use XToolkit in java applications
export AWT_TOOLKIT=XToolkit

# Load NVIDIA settings
nvidia-settings --load-config-only

# Adjust the monitor resolutions and positions
# xrandr --output VGA1 --mode 1680x1050 --right-of HDMI2

# Set background color
xsetroot -solid "#000000"

# Set the wallpaper
feh --bg-scale wallpapers/texture2.jpg

# Load Xresources (fonts, colors, etc...) for X11 apps
xrdb -merge ~/.Xresources

# Keyboard typing speed and delay
xset r rate 200 30

# Set the cursor icon when mouse is over the desktop
xsetroot -cursor_name left_ptr

# Disable bell
xset -b

# Enable zapping (C-A-<Bksp> kills X)
setxkbmap -option terminate:ctrl_alt_bksp

# Start the terminal daemon
urxvtd -q -f -o &

# Start the notification system
# dunst -fn "-*-liberation mono-medium-r-normal-*-12-*-96-96-*-*-*-*" \
#       -nb "#285577" -nf white -mod mod4 -key c -to 5 &

# Start the network manager
# wicd-gtk &

# Finally load the window manager
# exec i3 >> ~/.i3/logfile
exec enlightenment_start
