#!/bin/sh

# Load dbus for the X11 session
dbus_file="/etc/X11/xinit/xinitrc.d/30-dbus"
[ -x "$f" ] && . "$f"

# Set the env-var for the Gtk theme (Skype and Qt apps)
export GTK2_RC_FILES="$HOME/.gtkrc-2.0.mine"

# Load NVIDIA settings
# nvidia-settings --load-config-only
# nvidia-settings --assign="XVideoTextureSyncToVBlank=1" \
#		  --assign="SyncToVBlank=1"

# Adjust the monitor resolutions and positions
xrandr --output VGA1 --mode 1680x1050 --right-of HDMI2

# Set the wallpaper
sh ~/.fehbg

# Load Xresources (fonts, colors, etc...) for X11 apps
xrdb -merge ~/.Xresources

# Keyboard typing speed and delay
xset r rate 200 30

# Set the cursor icon when over the desktop
xsetroot -cursor_name left_ptr

# Load the system tray
# trayer --widthtype request --SetDockType true \
#	 --SetPartialStrut true --edge bottom \
#	 --align right --height 18 --transparent true \
#	 --tint 0 --alpha 0 &

dunst -fn "-*-liberation mono-medium-r-normal-*-12-*-96-96-*-*-*-*" \
      -bg "#285577" -fg white -mod mod4 -key c -to 5 &

# Load terminal daemon to save memory when there are 
#      a lot of client loaded
urxvtd -q -f -o &

# Finally load the window manager
exec i3
