#!/bin/bash

set -o nounset

HNAME=$(hostnamectl hostname)
echo "Status: Hostname $HNAME"

XPATH=$(realpath "$0")
echo "Status: Path $XPATH"

DPATH=$(dirname "$XPATH")
echo "Status: Dir $DPATH"

onroot () {
  if [ "$(echo "$1" | cut -c -6)" = "/home/" ]; then
    return 10
  else
    return 11
  fi
}

dosudo () {
  onroot "$2"

  if [ $? = 11 ]; then
    $SHELL -c "sudo $1 $2"
  else
    $SHELL -c "$1 $2"
  fi
}

cmerge () {
  if [[ -n "${3:+x}" ]]; then
    echo "Error: cmerge() requires 2 parameters, got 3: $1, $2, $3"
    exit 1
  fi

  SRC="$1"                              # source
  HSRC="$SRC.$HNAME"                    # host-specific source
  DST="$2"                              # destination

  if [ -f "$SRC" ]; then
    # common
    # echo "Status: Found $PSRC -> $DST"
    SRC="$SRC"
  elif [ -f "$HSRC" ]; then
    # host-specific
    # echo "Status: Found $PHSRC -> $DST"
    SRC="$HSRC"
  else
    echo "Might-Skip:"
    echo "  $DPATH/$SRC does not exist"
    echo "  $DPATH/$HSRC does not exist"

    if [ -f "$DST" ]; then
      echo "Not-Skip: $DST -> {$HSRC}"
      cp -i "$DST" "$DPATH/$HSRC"
    else
      echo "Skip: File $DST does not exist either"
    fi

    return
  fi

  if [ -e "$DST" ]; then
    if [ -f "$DST" ]; then
      if diff "$DPATH/$SRC" "$DST" 1>/dev/null 2>&1 ; then
        echo "Skip: {$SRC} === $DST"
      else
        echo "Merge: {$SRC} != $DST"
        dosudo "vim -f -d $DPATH/$SRC" "$DST"
      fi
    else
      echo "Error: $DST exists but is not a file"
      exit 1
    fi
  else
    DSTDIRNAME=$(dirname "$DST")
    echo "Create: $DSTDIRNAME"
    dosudo "mkdir -p" "$DSTDIRNAME"
    echo "Copy: {$SRC} -> $DST"
    dosudo "cp -i $DPATH/$SRC" "$DST"
  fi
}

echo "Applying generic Gnome settings..."
dconf load / < gnome.dconf
if [ -f "gnome.dconf.$HNAME" ]; then
  echo "Applying Gnome settings for $HNAME..."
  dconf load / < "gnome.dconf.$HNAME"
fi

for file in applications/*.desktop; do
  cmerge "$file" ~/.local/share/"$file"
done

cmerge bash/rc                       ~/.bashrc
cmerge bash/profile                  ~/.bash_profile
cmerge profile                       ~/.profile
cmerge inputrc                       ~/.config/readline/inputrc
cmerge vimrc                         ~/.config/vim/vimrc

cmerge dict/hunspell_en_US           ~/.hunspell_en_US
cmerge dict/aspell.en.pws            ~/.aspell.en.pws

cmerge gtk/bookmarks                 ~/.config/gtk-3.0/bookmarks

cmerge emacs/init.el                 ~/.config/emacs/init
cmerge emacs/early-init.el           ~/.config/emacs/early-init.el

cmerge fonts.conf                    ~/.config/fontconfig/fonts.conf
cmerge htoprc                        ~/.config/htop/htoprc
cmerge yt-dlp.conf                   ~/.config/yt-dlp/config

cmerge mpv/input.conf                ~/.config/mpv/input.conf
cmerge mpv/mpv.conf                  ~/.config/mpv/mpv.conf

cmerge git/config                    ~/.config/git/config
cmerge git/config-powerdns           ~/.config/git/config-powerdns

cmerge weechat/irc.conf              ~/.config/weechat/irc.conf
cmerge weechat/spell.conf            ~/.config/weechat/spell.conf
cmerge weechat/weechat.conf          ~/.config/weechat/weechat.conf

cmerge loader/loader.conf            /boot/loader/loader.conf
cmerge loader/arch.conf              /boot/loader/entries/arch.conf

cmerge gvfs-network.mount            /usr/share/gvfs/mounts/network.mount

cmerge archlinux/makepkg.conf        /etc/makepkg.conf
cmerge archlinux/mkinitcpio.conf     /etc/mkinitcpio.conf
cmerge archlinux/pacman.conf         /etc/pacman.conf
cmerge archlinux/paru.conf           /etc/paru.conf

cmerge net/hostname                  /etc/hostname
cmerge net/hosts                     /etc/hosts

cmerge personal.us.map               /usr/local/share/kbd/keymaps/personal.us.map
cmerge vconsole.conf                 /etc/vconsole.conf
cmerge locale.conf                   /etc/locale.conf
cmerge limits.conf                   /etc/security/limits.conf
cmerge sysctl/sysctl.conf            /etc/sysctl.d/sysctl.conf
cmerge sysctl/i915.conf              /etc/sysctl.d/i915.conf

cmerge modules/modprobe.conf         /etc/modprobe.d/modprobe.conf
cmerge modules/amdgpu.conf           /etc/modprobe.d/amdgpu.conf
cmerge modules/nvidia.conf           /etc/modprobe.d/nvidia.conf
cmerge modules/wifi.conf             /etc/modprobe.d/wifi.conf

cmerge x11/gdm-custom.conf           /etc/gdm/custom.conf
cmerge x11/00-system.conf            /etc/X11/xorg.conf.d/00-system.conf

cmerge docker.json                   /etc/docker/daemon.json
cmerge pythonrc                      /etc/python/pythonrc

SYSD=/etc/systemd

cmerge systemd/coredump.conf         $SYSD/coredump.conf
cmerge systemd/system.conf           $SYSD/system.conf
cmerge systemd/journald.conf         $SYSD/journald.conf
cmerge systemd/resolved.conf         $SYSD/resolved.conf
cmerge systemd/boot-override.conf    $SYSD/system/boot.mount.d/override.conf

cmerge vpn/ox.service                $SYSD/system/ox.service
cmerge vpn/ox-suspend.service        $SYSD/system/ox-suspend.service
cmerge vpn/ox-resume.service         $SYSD/system/ox-resume.service

if [ -f /etc/os-release ]; then
  if grep -i "archlinux" /etc/os-release 1>/dev/null 2>&1 ; then
    pkgs_tmp_file=$(mktemp)
    pacman -Qtteq | sort > "$pkgs_tmp_file"
    cmerge "pkgs/pacman.list" "$pkgs_tmp_file"
    pkgs_install=$(comm --check-order -2 -3 "pkgs/pacman.list.$HNAME" "$pkgs_tmp_file" | tr '\n' ' ')
    pkgs_remove=$(comm --check-order -1 -3 "pkgs/pacman.list.$HNAME" "$pkgs_tmp_file" | tr '\n' ' ')
    rm "$pkgs_tmp_file"

    if [ "$pkgs_remove" != "" ]; then
      echo "Remove packages:"
      $SHELL -c "sudo pacman -Rcsn $pkgs_remove"
    fi

    install_happened=0

    if [ "$pkgs_install" != "" ]; then
      echo "Install packages:"
      $SHELL -c "sudo pacman -Sy --needed $pkgs_install"
      install_happened=1
    fi

    echo "Update System"
    if [ $install_happened == 0 ]; then
      paru -Syu
    else
      paru -Su
    fi
  fi
fi

flatpak_tmp_file=$(mktemp)
flatpak --user list --app --columns=application > "$flatpak_tmp_file"
cmerge "pkgs/flatpak.list" "$flatpak_tmp_file"
flatpak_install=$(comm -2 -3 "pkgs/flatpak.list" "$flatpak_tmp_file" | tr '\n' ' ')
flatpak_remove=$(comm -1 -3 "pkgs/flatpak.list" "$flatpak_tmp_file" | tr '\n' ' ')
rm "$flatpak_tmp_file"

if [ "$flatpak_remove" != "" ]; then
  echo "Remove Flatpaks:"
  $SHELL -c "flatpak --user remove --app $flatpak_remove"
fi

if [ "$flatpak_install" != "" ]; then
  echo "Install Flatpaks:"
  $SHELL -c "flatpak --user install $flatpak_install"
fi

flatpak --user update
flatpak --user uninstall --unused

pkgs_cargo_tmp_file=$(mktemp)
cargo install --list | grep -E ':$' | awk '{ print $1 }' > "$pkgs_cargo_tmp_file"
cmerge "pkgs/cargo.list" "$pkgs_cargo_tmp_file"
pkgs_cargo_install=$(comm --check-order -2 -3 "pkgs/cargo.list" "$pkgs_cargo_tmp_file" | tr '\n' ' ')
pkgs_cargo_remove=$(comm --check-order -1 -3 "pkgs/cargo.list" "$pkgs_cargo_tmp_file" | tr '\n' ' ')
rm "$pkgs_cargo_tmp_file"

if [ "$pkgs_cargo_remove" != "" ]; then
  echo "Remove Cargo packages:"
  $SHELL -c "cargo uninstall $pkgs_cargo_remove"
fi

if [ "$pkgs_cargo_install" != "" ]; then
  echo "Install Cargo packages:"
  $SHELL -c "cargo binstall $pkgs_cargo_install"
fi
