# Graphics
XFWM4_USE_PRESENT=1
LIBVA_DRIVER_NAME=iHD
MESA_LOADER_DRIVER_OVERRIDE=iris

export XFWM4_USE_PRESENT LIBVA_DRIVER_NAME MESA_LOADER_DRIVER_OVERRIDE

# Path
PATH="$HOME/.cargo/bin:$PATH"
PATH="$HOME/.local/bin:$PATH"
PATH="$HOME/Workspace/dots/scripts:$PATH"
PATH="$HOME/Documents/Workspace/bin:$PATH"

# Rust
RUSTC_WRAPPER=sccache

# Editors
EDITOR='emacs -nw'
GIT_EDITOR=vim

export PATH EDITOR GIT_EDITOR RUSTC_WRAPPER
