git_repos = [
  "~/Workspace/attic",
  "~/Workspace/dots"
]

remote_topgrades = ["neuron", "synapse"]
remote_timeout = 2

[pre_commands]
"Emacs Snapshot" = "rm -rf ~/.emacs.d/elpa.bak && cp -rl ~/.emacs.d/elpa ~/.emacs.d/elpa.bak"
