#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

export PATH=~/.cabal/bin:~/bin:$PATH
export LD_LIBRARY_PATH=~/.cabal/lib:$LD_LIBRARY_PATH

alias cdrpi='cd /home/fred/Workspace/Projects/rpi'
