#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

export PATH=/home/fnm/.cabal/bin:/home/fnm/opt/bin:$PATH:/usr/local/bin
