#!/bin/sh

set -o posix
set -o errexit
set -o nounset
set -o pipefail

run_rsync () {
  echo ">>> $1 --> $2"
  rsync -ahH --delete --progress --xattrs --acls \
        /home/fred/"$1" \
        /run/media/fred/MyFiles/"$2"/
}

for i in Media Music Music.New Pictures; do
  run_rsync "$i" "Common"
done

for i in CommonDocs Documents Downloads HLaptop People Workspace; do
  run_rsync "$i" "Fred"
done

for i in VPN .config .getmail .gnupg .ssh; do
  run_rsync "$i" "Fred"
done
