#!/bin/bash

set -o pipefail
set -o errexit
set -o nounset
set -o noglob

CMD=("rsync"
     "-hhh"
     "--verbose"
     "--info=progress2"
     "--archive"
     "--executability"
     "--delete"
     "--delete-excluded"
     "--exclude=*/cargo-target"
     "--exclude=*/rustup"
     "--exclude=*/target"
     "--exclude=*/__pycache__"
     '--exclude=emacs/elpa/***'
     '--exclude=node_modules/***'
     '--exclude=clangd/*'
     '--exclude=share/flatpak/***'
     '--exclude=share/rust/***'
     "$@")

echo ">>> Rsync command:" "${CMD[@]}"

cmd () {
  printf ">>> %s --> %s\n" "$1" "$2"
  "${CMD[@]}" "$1" "$2"
  printf "\n\n"
}

HOSTNAME=$(hostnamectl hostname)
printf ">>> Hostname = %s\n\n\n" "$HOSTNAME"

HOME='/home/fred'
INTERNAL_DATA='/run/media/fred/Internal'
INTERNAL_MEDIA='/run/media/fred/Internal Media'
EXTERNAL_DATA='/run/media/fred/External Data'
PORTABLE_DATA='/run/media/fred/Portable Data'
PORTABLE_OX='/run/media/fred/Portable OX'

if [ "$HOSTNAME" == "axon" ]; then
  if [ -d "$INTERNAL_DATA" ]; then
    cmd "$HOME/Archive/"                  "$INTERNAL_DATA/Fred/Archive/"
    cmd "$HOME/Documents/"                "$INTERNAL_DATA/Fred/Documents/"
    cmd "$HOME/Downloads/"                "$INTERNAL_DATA/Fred/Downloads/"
    cmd "$HOME/Music/"                    "$INTERNAL_DATA/Fred/Music/"
    cmd "$HOME/Music.New/"                "$INTERNAL_DATA/Fred/Music.New/"
    cmd "$HOME/Phone/"                    "$INTERNAL_DATA/Fred/Phone/"
    cmd "$HOME/Pictures/"                 "$INTERNAL_DATA/Fred/Pictures/"
    cmd "$HOME/Videos/"                   "$INTERNAL_DATA/Fred/Videos/"
    cmd "$HOME/Workspace/"                "$INTERNAL_DATA/Fred/Workspace/"

    cmd "$HOME/.ssh/"                     "$INTERNAL_DATA/Fred/Configs/ssh/"
    cmd "$HOME/.config/beets/"            "$INTERNAL_DATA/Fred/Configs/config-beets/"
    cmd "$HOME/.config/MusicBrainz/"      "$INTERNAL_DATA/Fred/Configs/config-MusicBrainz/"
    cmd "$HOME/.config/qBittorrent/"      "$INTERNAL_DATA/Fred/Configs/config-qBittorrent/"
    cmd "$HOME/.config/protonvpn/"        "$INTERNAL_DATA/Fred/Configs/config-protonvpn/"
    cmd "$HOME/.config/quodlibet/"        "$INTERNAL_DATA/Fred/Configs/config-quodlibet/"
    cmd "$HOME/.config/yt-dlp/"           "$INTERNAL_DATA/Fred/Configs/config-yt-dlp/"
    cmd "$HOME/.local/share/gnupg/"       "$INTERNAL_DATA/Fred/Configs/local-share-gnupg/"
    cmd "$HOME/.local/share/keyrings/"    "$INTERNAL_DATA/Fred/Configs/local-share-keyrings/"
  else
    printf ">>> %s is not mounted\n" "$INTERNAL_DATA"
  fi

  if [ -d "$INTERNAL_MEDIA" ]; then
    cmd "$HOME/Archive/"                  "$INTERNAL_MEDIA/Fred/Archive/"
    cmd "$HOME/Documents/"                "$INTERNAL_MEDIA/Fred/Documents/"
    cmd "$HOME/Downloads/"                "$INTERNAL_MEDIA/Fred/Downloads/"
    cmd "$HOME/Music/"                    "$INTERNAL_MEDIA/Fred/Music/"
    cmd "$HOME/Music.New/"                "$INTERNAL_MEDIA/Fred/Music.New/"
    cmd "$HOME/Phone/"                    "$INTERNAL_MEDIA/Fred/Phone/"
    cmd "$HOME/Pictures/"                 "$INTERNAL_MEDIA/Fred/Pictures/"
    cmd "$HOME/Videos/"                   "$INTERNAL_MEDIA/Fred/Videos/"
    cmd "$HOME/Workspace/"                "$INTERNAL_MEDIA/Fred/Workspace/"

    cmd "$HOME/.ssh/"                     "$INTERNAL_MEDIA/Fred/Configs/ssh/"
    cmd "$HOME/.config/beets/"            "$INTERNAL_MEDIA/Fred/Configs/config-beets/"
    cmd "$HOME/.config/MusicBrainz/"      "$INTERNAL_MEDIA/Fred/Configs/config-MusicBrainz/"
    cmd "$HOME/.config/qBittorrent/"      "$INTERNAL_MEDIA/Fred/Configs/config-qBittorrent/"
    cmd "$HOME/.config/protonvpn/"        "$INTERNAL_MEDIA/Fred/Configs/config-protonvpn/"
    cmd "$HOME/.config/quodlibet/"        "$INTERNAL_MEDIA/Fred/Configs/config-quodlibet/"
    cmd "$HOME/.config/yt-dlp/"           "$INTERNAL_MEDIA/Fred/Configs/config-yt-dlp/"
    cmd "$HOME/.local/share/gnupg/"       "$INTERNAL_MEDIA/Fred/Configs/local-share-gnupg/"
    cmd "$HOME/.local/share/keyrings/"    "$INTERNAL_MEDIA/Fred/Configs/local-share-keyrings/"

    cmd "$INTERNAL_DATA/FredOther/"       "$INTERNAL_MEDIA/FredOther/"
    cmd "$INTERNAL_DATA/MediaStorage/"    "$INTERNAL_MEDIA/MediaStorage/"
  else
    printf ">>> %s is not mounted\n" "$INTERNAL_MEDIA"
  fi

  if [ -d "$PORTABLE_DATA" ]; then
    cmd "$HOME/Archive/"                  "$PORTABLE_DATA/Fred/Archive/"
    cmd "$HOME/Documents/"                "$PORTABLE_DATA/Fred/Documents/"
    cmd "$HOME/Downloads/"                "$PORTABLE_DATA/Fred/Downloads/"
    cmd "$HOME/Music/"                    "$PORTABLE_DATA/Fred/Music/"
    cmd "$HOME/Music.New/"                "$PORTABLE_DATA/Fred/Music.New/"
    cmd "$HOME/Phone/"                    "$PORTABLE_DATA/Fred/Phone/"
    cmd "$HOME/Pictures/"                 "$PORTABLE_DATA/Fred/Pictures/"
    cmd "$HOME/Videos/"                   "$PORTABLE_DATA/Fred/Videos/"
    cmd "$HOME/Workspace/"                "$PORTABLE_DATA/Fred/Workspace/"

    cmd "$HOME/.ssh/"                     "$PORTABLE_DATA/Fred/Configs/ssh/"
    cmd "$HOME/.config/beets/"            "$PORTABLE_DATA/Fred/Configs/config-beets/"
    cmd "$HOME/.config/MusicBrainz/"      "$PORTABLE_DATA/Fred/Configs/config-MusicBrainz/"
    cmd "$HOME/.config/qBittorrent/"      "$PORTABLE_DATA/Fred/Configs/config-qBittorrent/"
    cmd "$HOME/.config/protonvpn/"        "$PORTABLE_DATA/Fred/Configs/config-protonvpn/"
    cmd "$HOME/.config/quodlibet/"        "$PORTABLE_DATA/Fred/Configs/config-quodlibet/"
    cmd "$HOME/.config/yt-dlp/"           "$PORTABLE_DATA/Fred/Configs/config-yt-dlp/"
    cmd "$HOME/.local/share/gnupg/"       "$PORTABLE_DATA/Fred/Configs/local-share-gnupg/"
    cmd "$HOME/.local/share/keyrings/"    "$PORTABLE_DATA/Fred/Configs/local-share-keyrings/"

    cmd "$INTERNAL_DATA/FredOther/"       "$PORTABLE_DATA/FredOther/"
  else
    printf ">>> %s is not mounted\n" "$PORTABLE_DATA"
  fi

  if [ -d "$EXTERNAL_DATA" ]; then
    cmd "$HOME/Archive/"                  "$EXTERNAL_DATA/Fred/Archive/"
    cmd "$HOME/Documents/"                "$EXTERNAL_DATA/Fred/Documents/"
    cmd "$HOME/Downloads/"                "$EXTERNAL_DATA/Fred/Downloads/"
    cmd "$HOME/Music/"                    "$EXTERNAL_DATA/Fred/Music/"
    cmd "$HOME/Music.New/"                "$EXTERNAL_DATA/Fred/Music.New/"
    cmd "$HOME/Phone/"                    "$EXTERNAL_DATA/Fred/Phone/"
    cmd "$HOME/Pictures/"                 "$EXTERNAL_DATA/Fred/Pictures/"
    cmd "$HOME/Videos/"                   "$EXTERNAL_DATA/Fred/Videos/"
    cmd "$HOME/Workspace/"                "$EXTERNAL_DATA/Fred/Workspace/"

    cmd "$HOME/.ssh/"                     "$EXTERNAL_DATA/Fred/Configs/ssh/"
    cmd "$HOME/.config/beets/"            "$EXTERNAL_DATA/Fred/Configs/config-beets/"
    cmd "$HOME/.config/MusicBrainz/"      "$EXTERNAL_DATA/Fred/Configs/config-MusicBrainz/"
    cmd "$HOME/.config/qBittorrent/"      "$EXTERNAL_DATA/Fred/Configs/config-qBittorrent/"
    cmd "$HOME/.config/protonvpn/"        "$EXTERNAL_DATA/Fred/Configs/config-protonvpn/"
    cmd "$HOME/.config/quodlibet/"        "$EXTERNAL_DATA/Fred/Configs/config-quodlibet/"
    cmd "$HOME/.config/yt-dlp/"           "$EXTERNAL_DATA/Fred/Configs/config-yt-dlp/"
    cmd "$HOME/.local/share/gnupg/"       "$EXTERNAL_DATA/Fred/Configs/local-share-gnupg/"
    cmd "$HOME/.local/share/keyrings/"    "$EXTERNAL_DATA/Fred/Configs/local-share-keyrings/"

    cmd "$INTERNAL_DATA/FredOther/"       "$EXTERNAL_DATA/FredOther/"
  else
    printf ">>> %s is not mounted\n" "$EXTERNAL_DATA"
  fi
elif [ "$HOSTNAME" == "neuron" ]; then
  if [ -d "$PORTABLE_DATA" ]; then
    cmd "$HOME/Documents/"                "$PORTABLE_DATA/Laptop/Documents/"
    cmd "$HOME/Downloads/"                "$PORTABLE_DATA/Laptop/Downloads/"
    cmd "$HOME/Phone/"                    "$PORTABLE_DATA/Laptop/Phone/"
    cmd "$HOME/Pictures/"                 "$PORTABLE_DATA/Laptop/Pictures/"
    cmd "$HOME/Videos/"                   "$PORTABLE_DATA/Laptop/Videos/"
    cmd "$HOME/Workspace/"                "$PORTABLE_DATA/Laptop/Workspace/"

    cmd "$HOME/.ssh/"                     "$PORTABLE_DATA/Laptop/Configs/ssh/"
    cmd "$HOME/.config/beets/"            "$PORTABLE_DATA/Laptop/Configs/config-beets/"
    cmd "$HOME/.config/MusicBrainz/"      "$PORTABLE_DATA/Laptop/Configs/config-MusicBrainz/"
    cmd "$HOME/.config/qBittorrent/"      "$PORTABLE_DATA/Laptop/Configs/config-qBittorrent/"
    cmd "$HOME/.config/protonvpn/"        "$PORTABLE_DATA/Laptop/Configs/config-protonvpn/"
    cmd "$HOME/.config/quodlibet/"        "$PORTABLE_DATA/Laptop/Configs/config-quodlibet/"
    cmd "$HOME/.config/yt-dlp/"           "$PORTABLE_DATA/Laptop/Configs/config-yt-dlp/"
    cmd "$HOME/.local/share/gnupg/"       "$PORTABLE_DATA/Laptop/Configs/local-share-gnupg/"
    cmd "$HOME/.local/share/keyrings/"    "$PORTABLE_DATA/Laptop/Configs/local-share-keyrings/"
  else
    printf ">>> %s is not mounted\n" "$PORTABLE_DATA"
  fi

  if [ -d "$PORTABLE_OX" ]; then
    cmd "$HOME/Archive/"                  "$PORTABLE_OX/Laptop/Archive/"
    cmd "$HOME/Documents/"                "$PORTABLE_OX/Laptop/Documents/"
    cmd "$HOME/Downloads/"                "$PORTABLE_OX/Laptop/Downloads/"
    cmd "$HOME/Music/"                    "$PORTABLE_OX/Laptop/Music/"
    cmd "$HOME/Music.New/"                "$PORTABLE_OX/Laptop/Music.New/"
    cmd "$HOME/Phone/"                    "$PORTABLE_OX/Laptop/Phone/"
    cmd "$HOME/Pictures/"                 "$PORTABLE_OX/Laptop/Pictures/"
    cmd "$HOME/Videos/"                   "$PORTABLE_OX/Laptop/Videos/"
    cmd "$HOME/Workspace/"                "$PORTABLE_OX/Laptop/Workspace/"

    cmd "$HOME/.config/"                  "$PORTABLE_OX/Laptop/Configs/dot.config/"
    cmd "$HOME/.cache/"                   "$PORTABLE_OX/Laptop/Configs/dot.cache/"
    cmd "$HOME/.local/"                   "$PORTABLE_OX/Laptop/Configs/dot.local/"
    cmd "$HOME/.mozilla/"                 "$PORTABLE_OX/Laptop/Configs/dot.mozilla/"
    cmd "$HOME/.ssh/"                     "$PORTABLE_OX/Laptop/Configs/dot.ssh/"
  else
    printf ">>> %s is not mounted\n" "$PORTABLE_OX"
  fi
else
  printf ">>> Unknown machine with hostname = %s\n" "$HOSTNAME"
  exit 1
fi
