#!/bin/sh

# set -o posix
# set -o pipefail
set -o errexit
set -o nounset

HOME=/home/fred

bk_cmd () {
  echo ">>> $1 --> $2:"
  rsync "-ahH" "--delete" "--progress" "--xattrs" "--acls" "--delete-excluded" '--exclude="*/target"' "$1" "$2"
  echo ">>> ------ <<<"
}

if [ "$(hostname)" = "floron" ]; then
  echo "Floron backup"

  DST=

  bk_cmd  "$HOME/.gnupg/"                 "$DST/Data/Fred/Configs/Laptop/gnupg/"
  bk_cmd  "$HOME/.ssh/"                   "$DST/Data/Fred/Configs/Laptop/ssh/"
  bk_cmd  "$HOME/.config/beets/"          "$DST/Data/Fred/Configs/Laptop/config-beets/"
  bk_cmd  "$HOME/.config/hexchat/"        "$DST/Data/Fred/Configs/Laptop/config-hexchat/"
  bk_cmd  "$HOME/.config/MusicBrainz/"    "$DST/Data/Fred/Configs/Laptop/config-MusicBrainz/"
  bk_cmd  "$HOME/.config/transmission/"   "$DST/Data/Fred/Configs/Laptop/config-transmission/"
  bk_cmd  "$HOME/.config/youtube-dl/"     "$DST/Data/Fred/Configs/Laptop/config-youtube-dl/"
  bk_cmd  "$HOME/.local/share/keyrings"   "$DST/Data/Fred/Configs/Laptop/local-share-keyrings/"

  bk_cmd  "$HOME/.thunderbird/"           "$DST/Data/Fred/Configs/Laptop/thunderbird/"
  bk_cmd  "$HOME/.idealgraphvisualizer/"  "$DST/Data/Fred/Configs/Laptop/idealgraphvisualizer/"
  bk_cmd  "$HOME/.eclipse/"               "$DST/Data/Fred/Configs/Laptop/eclipse/"
  bk_cmd  "$HOME/.zoom/"                  "$DST/Data/Fred/Configs/Laptop/zoom/"
  bk_cmd  "$HOME/.tree-sitter/"           "$DST/Data/Fred/Configs/Laptop/tree-sitter/"

  bk_cmd  "$HOME/.face"                   "$DST/Data/Fred/Configs/Laptop/face"
  bk_cmd  "$HOME/.wallpaper.jpg"          "$DST/Data/Fred/Configs/Laptop/wallpaper.jpg"
  bk_cmd  "$HOME/.wallpaper_old.jpg"      "$DST/Data/Fred/Configs/Laptop/wallpaper_old.jpg"
elif [ "$(hostname)" = "axon" ]; then
  echo "Axon backup"

  bk_cmd  "$HOME/Archive/"                "$HDD/Fred/Archive/"
  bk_cmd  "$HOME/Books/"                  "$HDD/Fred/Books/"
  bk_cmd  "$HOME/Documents/"              "$HDD/Fred/Documents/"
  bk_cmd  "$HOME/Downloads/"              "$HDD/Fred/Downloads/"
  bk_cmd  "$HOME/GMail/"                  "$HDD/Fred/GMail/"
  bk_cmd  "$HOME/Music/"                  "$HDD/Fred/Music/"
  bk_cmd  "$HOME/Music.New/"              "$HDD/Fred/Music.New/"
  bk_cmd  "$HOME/Videos/"                 "$HDD/Fred/Videos/"
  bk_cmd  "$HOME/VideosCS/"               "$HDD/Fred/VideosCS/"
  bk_cmd  "$HOME/Workspace/"              "$HDD/Fred/Workspace/"
else
  echo "Unknown host, not doing any backups"
fi
