#!/bin/bash

set -o pipefail
set -o errexit
set -o nounset
set -o noglob

CMD=("rsync"
     "--human-readable"
     "--progress"
     "--archive"
     "--xattrs"
     "--acls"
     # "-zz"
     # "--preallocate"
     # "--sparse"
     "--delete"
     # "--delete-after"
     "--delete-excluded"
     "--exclude=*/target"
     "--hard-links"
     # "--safe-links"
     # "--munge-links"
     "$@")

echo "Rsync command: " "${CMD[@]}"

cmd () {
  echo ">>> ------ $1 --> $2:"
  "${CMD[@]}" "$1" "$2"
  echo ""
  echo ""
}

HOME=/home/fred
FLORON="fred@floron:$HOME"
EXTERNAL=/run/media/fred/External
FRED="$EXTERNAL/Fred"
LAPTOP="$FRED/Laptop"

cmd "$FLORON/GMail/"                  "$LAPTOP/GMail/"
cmd "$FLORON/Workspace/"              "$LAPTOP/Workspace/"
cmd "$FLORON/.gnupg/"                 "$LAPTOP/Configs/gnupg/"
cmd "$FLORON/.ssh/"                   "$LAPTOP/Configs/ssh/"
cmd "$FLORON/.config/beets/"          "$LAPTOP/Configs/config-beets/"
cmd "$FLORON/.config/hexchat/"        "$LAPTOP/Configs/config-hexchat/"
cmd "$FLORON/.config/MusicBrainz/"    "$LAPTOP/Configs/config-MusicBrainz/"
cmd "$FLORON/.config/transmission/"   "$LAPTOP/Configs/config-transmission/"
cmd "$FLORON/.config/youtube-dl/"     "$LAPTOP/Configs/config-youtube-dl/"
cmd "$FLORON/.local/share/keyrings"   "$LAPTOP/Configs/local-share-keyrings/"
cmd "$FLORON/.face"                   "$LAPTOP/Configs/face.png"
cmd "$FLORON/.wallpaper.jpg"          "$LAPTOP/Configs/wallpaper.jpg"
cmd "$FLORON/.thunderbird/"           "$LAPTOP/Configs/oracle-thunderbird/"
cmd "$FLORON/.idealgraphvisualizer/"  "$LAPTOP/Configs/oracle-idealgraphvisualizer/"
cmd "$FLORON/.eclipse/"               "$LAPTOP/Configs/oracle-eclipse/"
cmd "$FLORON/.zoom/"                  "$LAPTOP/Configs/oracle-zoom/"

cmd "$HOME/Hilda/"                    "$EXTERNAL/Hilda/"

cmd "$HOME/Archive/"                  "$FLORON/Archive/"
cmd "$HOME/Music/"                    "$FLORON/Music/"
cmd "$HOME/Music.New/"                "$FLORON/Music.New/"

cmd "$HOME/Archive/"                  "$FRED/Archive/"
cmd "$HOME/Music/"                    "$FRED/Music/"
cmd "$HOME/Music.New/"                "$FRED/Music.New/"

cmd "$HOME/Documents/"                "$FRED/Documents/"
cmd "$HOME/Downloads/"                "$FRED/Downloads/"
cmd "$HOME/Phone/"                    "$FRED/Phone/"
cmd "$HOME/Videos/"                   "$FRED/Videos/"
cmd "$HOME/VideosCS/"                 "$FRED/VideosCS/"
cmd "$HOME/Workspace/"                "$FRED/Workspace/"
cmd "$HOME/.gnupg/"                   "$FRED/Configs/gnupg/"
cmd "$HOME/.ssh/"                     "$FRED/Configs/ssh/"
cmd "$HOME/.config/beets/"            "$FRED/Configs/config-beets/"
cmd "$HOME/.config/hexchat/"          "$FRED/Configs/config-hexchat/"
cmd "$HOME/.config/MusicBrainz/"      "$FRED/Configs/config-MusicBrainz/"
cmd "$HOME/.config/transmission/"     "$FRED/Configs/config-transmission/"
cmd "$HOME/.config/youtube-dl/"       "$FRED/Configs/config-youtube-dl/"
cmd "$HOME/.local/share/keyrings"     "$FRED/Configs/local-share-keyrings/"
cmd "$HOME/.face"                     "$FRED/Configs/face.jpg"
cmd "$HOME/.wallpaper.jpg"            "$FRED/Configs/wallpaper.jpg"

# HOME=/home/fred
# FLORON="fred@floron:$HOME"
# DATA="$HOME/Data/Fred"
# LAPTOP="$DATA/Laptop"
# DESKTOP="$DATA/Desktop"
# EXTERNAL="/run/media/fred/External"

# cmd "$FLORON/GMail/"                  "$LAPTOP/GMail/"
# cmd "$FLORON/Workspace/"              "$LAPTOP/Workspace/"
# cmd "$FLORON/.gnupg/"                 "$LAPTOP/Configs/gnupg/"
# cmd "$FLORON/.ssh/"                   "$LAPTOP/Configs/ssh/"
# cmd "$FLORON/.config/beets/"          "$LAPTOP/Configs/config-beets/"
# cmd "$FLORON/.config/hexchat/"        "$LAPTOP/Configs/config-hexchat/"
# cmd "$FLORON/.config/MusicBrainz/"    "$LAPTOP/Configs/config-MusicBrainz/"
# cmd "$FLORON/.config/transmission/"   "$LAPTOP/Configs/config-transmission/"
# cmd "$FLORON/.config/youtube-dl/"     "$LAPTOP/Configs/config-youtube-dl/"
# cmd "$FLORON/.local/share/keyrings"   "$LAPTOP/Configs/local-share-keyrings/"
# cmd "$FLORON/.face"                   "$LAPTOP/Configs/face.png"
# cmd "$FLORON/.wallpaper.jpg"          "$LAPTOP/Configs/wallpaper.jpg"
# cmd "$FLORON/.thunderbird/"           "$LAPTOP/Configs/oracle-thunderbird/"
# cmd "$FLORON/.idealgraphvisualizer/"  "$LAPTOP/Configs/oracle-idealgraphvisualizer/"
# cmd "$FLORON/.eclipse/"               "$LAPTOP/Configs/oracle-eclipse/"
# cmd "$FLORON/.zoom/"                  "$LAPTOP/Configs/oracle-zoom/"

# cmd "$HOME/Archive/"                  "$FLORON/Archive/"
# cmd "$HOME/Music/"                    "$FLORON/Music/"
# cmd "$HOME/Music.New/"                "$FLORON/Music.New/"

# cmd "$HOME/Archive/"                  "$DATA/Archive/"
# cmd "$HOME/Music/"                    "$DATA/Music/"
# cmd "$HOME/Music.New/"                "$DATA/Music.New/"

# cmd "$HOME/Hilda/"                    "$HOME/Data/Hilda/"

# cmd "$HOME/Documents/"                "$DATA/Documents/"
# cmd "$HOME/Downloads/"                "$DATA/Downloads/"
# cmd "$HOME/Phone/"                    "$DATA/Phone/"
# cmd "$HOME/Videos/"                   "$DATA/Videos/"
# cmd "$HOME/VideosCS/"                 "$DATA/VideosCS/"
# cmd "$HOME/Workspace/"                "$DESKTOP/Workspace/"
# cmd "$HOME/.gnupg/"                   "$DESKTOP/Configs/gnupg/"
# cmd "$HOME/.ssh/"                     "$DESKTOP/Configs/ssh/"
# cmd "$HOME/.config/beets/"            "$DESKTOP/Configs/config-beets/"
# cmd "$HOME/.config/hexchat/"          "$DESKTOP/Configs/config-hexchat/"
# cmd "$HOME/.config/MusicBrainz/"      "$DESKTOP/Configs/config-MusicBrainz/"
# cmd "$HOME/.config/transmission/"     "$DESKTOP/Configs/config-transmission/"
# cmd "$HOME/.config/youtube-dl/"       "$DESKTOP/Configs/config-youtube-dl/"
# cmd "$HOME/.local/share/keyrings"     "$DESKTOP/Configs/local-share-keyrings/"
# cmd "$HOME/.face"                     "$DESKTOP/Configs/face.jpg"
# cmd "$HOME/.wallpaper.jpg"            "$DESKTOP/Configs/wallpaper.jpg"

# if [ -d "$EXTERNAL" ]; then
#   cmd "$HOME/Data/" "$EXTERNAL/"
# fi
