#!/bin/bash

set -o pipefail
set -o errexit
set -o nounset
set -o noglob

CMD=("rsync"
     "-hhh"
     "--verbose"
     "--info=progress2"
     "--archive"
     "--executability"
     "--delete"
     "--delete-excluded"
     "--exclude=*/target"
     "--exclude=*/__pycache__"
     '--exclude=emacs/elpa/*'
     '--exclude=node_modules/*'
     "$@")

echo "Rsync command:" "${CMD[@]}"
printf "\n\n"

cmd () {
    printf ">>> %s --> %s\n" "$1" "$2"
    "${CMD[@]}" "$1" "$2"
    printf "\n\n"
}

HOME=/home/fred
LAPTOP=/run/media/fred/External/Laptop

if [ -d $LAPTOP ]; then
    cmd "$HOME/Documents/"                "$LAPTOP/Documents/"
    cmd "$HOME/Downloads/"                "$LAPTOP/Downloads/"
    cmd "$HOME/Phone/"                    "$LAPTOP/Phone/"
    cmd "$HOME/Workspace/"                "$LAPTOP/Workspace/"
    cmd "$HOME/.gnupg/"                   "$LAPTOP/Configs/gnupg/"
    cmd "$HOME/.ssh/"                     "$LAPTOP/Configs/ssh/"
    cmd "$HOME/.config/transmission/"     "$LAPTOP/Configs/config-transmission/"
    cmd "$HOME/.config/yt-dlp/"           "$LAPTOP/Configs/config-yt-dlp/"
    cmd "$HOME/.config/syncthing/"        "$LAPTOP/Configs/config-syncthing/"
    cmd "$HOME/.local/share/keyrings/"    "$LAPTOP/Configs/local-share-keyrings/"
else
    printf ">>> %s is not mounted\n" $LAPTOP
    exit 1
fi
