#!/bin/bash

set -o pipefail
set -o errexit
set -o nounset
set -o noglob

CMD=("rsync"
     # "--preallocate"
     # "--sparse"
     # "--delete-after"
     # "--safe-links"
     # "--munge-links"
     # "--xattrs"
     # "--acls"
     # "--one-file-system"
     # "--hard-links"
     # "-zz"
     '--human-readable'
     '--progress'
     '--verbose'
     '--archive'
     '--skip-compress=zst/jpg/mp[34]/7z/bz2/webm/avi'
     '--delete'
     '--delete-excluded'
     '--exclude=target/*'
     '--exclude=__pycache__/*'
     '--exclude=Oracle/opt/*'
     '--exclude=mxbuild/*'
     '--exclude=eln-cache/*'
     '--exclude=discord/Cache/*'
     '--exclude=discord/Code Cache/*'
     '--exclude=discord/0.0.11/*'
     '--exclude=.incomplete/*'
     "$@")

echo "Rsync command:" "${CMD[@]}"
printf "\n\n"

cmd () {
    printf ">>> %s --> %s\n" "$1" "$2"
    "${CMD[@]}" "$1" "$2"
    printf "\n\n"
}

HOME=/home/fred
EXTERNAL=/run/media/fred/External/TMP

if [ -d $EXTERNAL ]; then
    cmd "$HOME/Documents/"              "$EXTERNAL/Documents/"
    cmd "$HOME/Downloads/"              "$EXTERNAL/Downloads/"
    cmd "$HOME/GMail/"                  "$EXTERNAL/GMail/"
    cmd "$HOME/ProtonMail/"             "$EXTERNAL/ProtonMail/"
    cmd "$HOME/Media/Torrents/"         "$EXTERNAL/Torrents/"
    cmd "$HOME/Oracle/"                 "$EXTERNAL/Oracle/"
    cmd "$HOME/Phone/"                  "$EXTERNAL/Phone/"
    cmd "$HOME/Videos/"                 "$EXTERNAL/Videos/"
    cmd "$HOME/Workspace/"              "$EXTERNAL/Workspace/"
    cmd "$HOME/.gnupg/"                 "$EXTERNAL/Configs/gnupg/"
    cmd "$HOME/.ssh/"                   "$EXTERNAL/Configs/ssh/"
    cmd "$HOME/.config/"                "$EXTERNAL/Configs/config/"
    cmd "$HOME/.local/share/keyrings"   "$EXTERNAL/Configs/local-share-keyrings/"
    cmd "$HOME/.local/share/fonts"      "$EXTERNAL/Configs/local-share-fonts/"
    cmd "$HOME/.face"                   "$EXTERNAL/Configs/face.png"
    cmd "$HOME/.thunderbird/"           "$EXTERNAL/Configs/oracle-thunderbird/"
    cmd "$HOME/.idealgraphvisualizer/"  "$EXTERNAL/Configs/oracle-idealgraphvisualizer/"
    cmd "$HOME/.eclipse/"               "$EXTERNAL/Configs/oracle-eclipse/"
    cmd "$HOME/.zoom/"                  "$EXTERNAL/Configs/oracle-zoom/"
else
    printf ">>> %s is not mounted\n" $EXTERNAL
    exit 1
fi
