#!/bin/sh

# set -o posix
# set -o pipefail
set -o errexit
set -o nounset

if [ "$1" = "intel" ] || [ "$1" = "in" ]; then
  optimus-manager --switch intel
fi

if [ "$1" = "nvidia" ] || [ "$1" = "nv" ]; then
  optimus-manager --switch nvidia
fi

loginctl terminate-session "$XDG_SESSION_ID"
