#!/bin/sh

# set -o posix
# set -o pipefail
set -o errexit
set -o nounset

if [ "$1" = "intel" ] || [ "$1" = "in" ]; then
  optimus-manager --switch intel
elif [ "$1" = "nvidia" ] || [ "$1" = "nv" ]; then
  optimus-manager --switch nvidia
else
  echo "Error: Only accept 'nvidia' or 'intel'"
  exit 1
fi

loginctl terminate-session "$XDG_SESSION_ID"
