#!/bin/sh

set -o errexit
set -o nounset

sudo rmmod ath10k_pci
sudo rmmod ath10k_core
sudo rmmod ath

sudo modprobe ath
sudo modprobe ath10k_core
sudo modprobe ath10k_pci

sudo systemctl restart NetworkManager
