#!/bin/bash

set -o pipefail
set -o errexit
set -o nounset
set -o noglob

CMD=("rsync"
     "-hhh"
     "--verbose"
     "--info=progress1,flist0,del1,copy1,backup1,misc0,name1,nonreg1,remove1,skip1,stats0,symsafe1"
     "--archive"
     "--executability"
     "--delete"
     "$@")

echo ">>> Rsync command:" "${CMD[@]}"

cmd () {
  printf ">>> %s --> %s\n" "$1" "$2"
  "${CMD[@]}" "$1" "$2"
}

DATA='/run/media/fred/Data'
MEDIA='/run/media/fred/Media'

if [ -d "$MEDIA" ]; then
  cmd "$DATA/Media/Documentaries/"              "rpi:/media/A/Documentaries/"
  cmd "$DATA/Media/Franchises/"                 "rpi:/media/A/Franchises/"
  cmd "$DATA/Media/Movies/"                     "rpi:/media/A/Movies/"
  cmd "$DATA/Media/Movies (Arabic)/"            "rpi:/media/A/Movies (Arabic)/"
  cmd "$DATA/Media/Movies (Good)/"              "rpi:/media/A/Movies (Good)/"
  cmd "$DATA/Media/Movies (Old)/"               "rpi:/media/A/Movies (Old)/"
  cmd "$DATA/Media/Movies (Romanian)/"          "rpi:/media/A/Movies (Romanian)/"
  cmd "$DATA/Media/Movies (Short)/"             "rpi:/media/A/Movies (Short)/"
  cmd "$DATA/Media/Movies (Unknown)/"           "rpi:/media/A/Movies (Unknown)/"
  cmd "$DATA/Media/Music Videos/"               "rpi:/media/A/Music Videos/"
  cmd "$DATA/Media/Standups/"                   "rpi:/media/A/Standups/"

  cmd "$MEDIA/Media/Series/"                    "rpi:/media/B/Series/"
  cmd "$MEDIA/Media/Series (Good)/"             "rpi:/media/B/Series (Good)/"
  cmd "$MEDIA/Media/Series (History)/"          "rpi:/media/B/Series (History)/"
  cmd "$MEDIA/Media/Series (Nature)/"           "rpi:/media/B/Series (Nature)/"
  cmd "$MEDIA/Media/Series (Unknown)/"          "rpi:/media/B/Series (Unknown)/"
else
  printf ">>> %s is not mounted\n" "$MEDIA"
fi
