#!/bin/bash

set -o pipefail
set -o errexit
set -o nounset
set -o noglob

CMD=("rsync"
     "-hhh"
     "--verbose"
     "--preallocate"
     "--info=progress1,flist0,del1,copy1,backup1,misc0,name1,nonreg1,remove1,skip1,stats0,symsafe1"
     "-rltD"
     "--executability"
     "--delete"
     "$@")

echo ">>> Rsync command:" "${CMD[@]}"

cmd () {
  printf ">>> %s --> %s\n" "$1" "$2"
  "${CMD[@]}" "$1" "$2"
}

DATA='/run/media/fred/Data'
MEDIA='/run/media/fred/Media'

if [ -d "$MEDIA" ]; then
  cmd "$DATA/Media/Franchises/"                 "rpi:/var/media/Media-A/Franchises/"
  cmd "$DATA/Media/Movies/"                     "rpi:/var/media/Media-A/Movies/"
  cmd "$DATA/Media/Movies (Arabic)/"            "rpi:/var/media/Media-A/Movies (Arabic)/"
  cmd "$DATA/Media/Movies (Good)/"              "rpi:/var/media/Media-A/Movies (Good)/"
  cmd "$DATA/Media/Movies (Old)/"               "rpi:/var/media/Media-A/Movies (Old)/"
  cmd "$DATA/Media/Movies (Short)/"             "rpi:/var/media/Media-A/Movies (Short)/"

  cmd "$MEDIA/Media/Documentaries/"             "rpi:/var/media/Media-B/Documentaries/"
  cmd "$MEDIA/Media/Music Videos/"              "rpi:/var/media/Media-B/Music Videos/"
  cmd "$MEDIA/Media/Series/"                    "rpi:/var/media/Media-B/Series/"
  cmd "$MEDIA/Media/Series (Good)/"             "rpi:/var/media/Media-B/Series (Good)/"
  cmd "$MEDIA/Media/Series (History)/"          "rpi:/var/media/Media-B/Series (History)/"
  cmd "$MEDIA/Media/Series (Nature)/"           "rpi:/var/media/Media-B/Series (Nature)/"
  cmd "$MEDIA/Media/Series (Unknown)/"          "rpi:/var/media/Media-B/Series (Unknown)/"
  cmd "$MEDIA/Media/Standups/"                  "rpi:/var/media/Media-B/Standups/"
else
  printf ">>> %s is not mounted\n" "$MEDIA"
fi
