#!/bin/bash

set -o pipefail
set -o errexit
set -o nounset
set -o noglob

CMD=("rsync"
     "-hhh"
     "--verbose"
     "--info=progress2"
     "--archive"
     "--executability"
     "--delete"
     "--delete-excluded"
     "--exclude=*/target"
     "--exclude=*/__pycache__"
     '--exclude=emacs/elpa/*'
     '--exclude=node_modules/*'
     '--exclude=clangd/*'
     "$@")

echo ">>> Rsync command:" "${CMD[@]}"

HNAME=$(hostnamectl hostname)
printf ">>> Hostname = %s\n\n\n" "$HNAME"

TARGET=""
if [ "$HNAME" == "axon" ]; then
    TARGET="neuron"
elif [ "$HNAME" == "neuron" ]; then
    TARGET="axon"
else
    printf ">>> Unknown machine with hostname = %s\n" "$HNAME"
    exit 1
fi

cmd () {
    TARGET_OBJ="$TARGET:/$1"
    printf ">>> %s --> %s\n" "$1" "$TARGET_OBJ"
    "${CMD[@]}" "$1" "$TARGET_OBJ"
    printf "\n\n"
}

rdiff () {
    TARGET_FILE="scp://$TARGET/$1"
    printf ">>> %s vs. %s" "$1" "$TARGET_FILE"
    vim -d "$1" "$TARGET_FILE"
    printf "\n\n"
}

HOME=/home/fred

rdiff $HOME/.ssh/authorized_keys
rdiff $HOME/.ssh/known_hosts
rdiff $HOME/.config/yt-dlp/archive

cmd $HOME/.ssh/
cmd $HOME/.config/yt-dlp/
cmd $HOME/.local/share/gnupg/
cmd $HOME/.local/share/keyrings/
