#!/bin/bash

set -o pipefail
set -o errexit
set -o nounset
set -o noglob

CMD=("rsync"
     "-hhh"
     "--verbose"
     "--info=progress2"
     "--archive"
     "--executability"
     "--delete"
     '--exclude=__pycache__'
     '--exclude=.mypy_cache'
     '--exclude=emacs/elpa/'
     '--exclude=node_modules/'
     '--exclude=.cache/clangd'
     '--exclude=.libs'
     "$@")

echo ">>> Rsync command:" "${CMD[@]}"

HOSTNAME=$(hostnamectl hostname)
printf ">>> Hostname = %s\n" "$HOSTNAME"

if [ -z ${TARGET+x} ]; then
  if [ "$HOSTNAME" == "axon" ]; then
    TARGET="neuron"
  elif [ "$HOSTNAME" == "neuron" ]; then
    TARGET="axon"
  else
    printf ">>> Unknown machine with hostname = %s\n" "$HOSTNAME"
    exit 1
  fi
fi

printf ">>> Target Machine is %s\n\n\n" "$TARGET"

cmd () {
  TARGET_OBJ="$TARGET:/$1"
  printf ">>> %s --> %s\n" "$1" "$TARGET_OBJ"
  "${CMD[@]}" "$1" "$TARGET_OBJ"
  printf "\n\n"
}

rdiff () {
  TARGET_FILE="scp://$TARGET/$1"
  printf ">>> %s vs. %s\n" "$1" "$TARGET_FILE"
  nvim -d "$1" "$TARGET_FILE"
  printf "\n\n"
}

HOME=/home/fred

rdiff $HOME/.ssh/authorized_keys
rdiff $HOME/.ssh/known_hosts
rdiff $HOME/.config/yt-dlp/archive

cmd $HOME/.ssh/

cmd $HOME/.config/MusicBrainz/
cmd $HOME/.config/beets/
cmd $HOME/.config/Proton/
cmd $HOME/.config/transmission/
cmd $HOME/.config/yt-dlp/

cmd $HOME/.local/share/authenticator/
cmd $HOME/.local/share/gnome-podcasts/
cmd $HOME/.local/share/gnupg/
cmd $HOME/.local/share/keyrings/

cmd $HOME/.cache/authenticator/
cmd $HOME/.cache/gnome-podcasts/
cmd $HOME/.cache/Proton/
cmd $HOME/.cache/transmission-qt/

cmd $HOME/Workspace/
