#!/bin/sh

set -o nounset

if [ -z "$PASSFILE" ]; then
  echo "Error: PASSFILE is empty or unset" >&2
  exit 1
fi

NMATCHES=$(grep -c "$@" "$PASSFILE")

if [ "$NMATCHES" != "1" ]; then
  echo "Error: More than 1 match for " "$@" >&2
  exit 1
fi

MATCH_INACTIVE=$(grep "$@" "$PASSFILE" | grep -cE '^-')

if [ "$MATCH_INACTIVE" != "0" ]; then
  echo "Warning: Account for " "$@" " is inactive" >&2
fi

MATCH_NEEDSCHANGE=$(grep "$@" "$PASSFILE" | grep -cE '^\*')

if [ "$MATCH_NEEDSCHANGE" != "0" ]; then
  echo "Warning: Account for " "$@" " needs a password change" >&2
fi

grep "$@" "$PASSFILE" | awk '{ print $4 }'
