#!/bin/sh

set -o errexit
set -o nounset

if [ -z "$PASSFILE" ]; then
  echo "Error: PASSFILE is empty or unset" >&2
  exit 1
fi

NCHANGE=$(grep -cE '^\*' "$PASSFILE")
NINACTIVE=$(grep -cE '^-' "$PASSFILE")

echo "$NCHANGE passwords need changing, $NINACTIVE are inactive"
