(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(TeX-auto-save t)
 '(TeX-master nil)
 '(TeX-parse-self t)
 '(auto-revert-interval 1)
 '(auto-save-file-name-transforms (\` ((".*" (\, emacs-autosaves-pattern) t))))
 '(auto-save-mode t)
 '(auto-window-vscroll nil t)
 '(backup-directory-alist (\` ((".*" \, emacs-backups-pattern))))
 '(backup-inhibited nil t)
 '(blink-cursor-mode nil)
 '(coding-system-for-read (quote utf-8-unix) t)
 '(coding-system-for-write (quote utf-8-unix) t)
 '(colon-double-space t)
 '(column-number-mode t)
 '(comment-auto-fill-only-comments t)
 '(comment-column 40)
 '(comment-empty-lines nil)
 '(comment-fill-column 70)
 '(comment-inline-offset 1)
 '(comment-multi-line t)
 '(comment-padding 1)
 '(comment-style (quote extra-line))
 '(cursor-in-non-selected-windows nil)
 '(default-justification (quote left))
 '(delete-old-versions t)
 '(dired-dwim-target t)
 '(dired-listing-switches "-alh --group-directories-first")
 '(dired-omit-files "^\\...+$")
 '(dired-use-ls-dired t)
 '(ediff-split-window-function (function split-window-horizontally))
 '(ediff-window-setup-function (function ediff-setup-windows-plain))
 '(fill-column 70)
 '(font-use-system-font nil)
 '(frame-title-format "%b - emacs" t)
 '(fringes-outside-margins t t)
 '(help-window-select t)
 '(highlight-nonselected-windows nil)
 '(history-delete-duplicates t)
 '(history-length 30)
 '(indent-tabs-mode nil)
 '(inhibit-compacting-font-caches t t)
 '(inhibit-startup-buffer-menu t)
 '(inhibit-startup-screen t)
 '(initial-major-mode (quote fundamental-mode))
 '(initial-scratch-message nil)
 '(ivy--regex-ignore-order t)
 '(ivy-count-format "(%d/%d) ")
 '(ivy-extra-directories (quote nil))
 '(ivy-regex-ignore-order t)
 '(ivy-use-selectable-prompt t)
 '(ivy-use-virtual-buffers t)
 '(ivy-wrap t)
 '(js-indent-level 2)
 '(json-reformat:indent-width 2)
 '(json-reformat:pretty-string\? t)
 '(load-prefer-newer t)
 '(make-backup-files t)
 '(menu-bar-mode nil)
 '(minibuffer-prompt-properties
   (quote
    (read-only t point-entered minibuffer-avoid-prompt face minibuffer-prompt)))
 '(mode-require-final-newline (quote visit-save))
 '(mouse-yank-at-point t)
 '(nxml-auto-insert-xml-declaration-flag t)
 '(nxml-sexp-element-flag t)
 '(nxml-slash-auto-complete-flag t)
 '(package-check-signature nil)
 '(package-selected-packages
   (quote
    (which-key flx ivy swiper counsel smex json-mode rust-mode toml-mode racer cargo pdf-tools hledger-mode lsp-mode lsp-ui company-lsp)))
 '(recentf-mode t)
 '(recentf-save-file emacs-recentf-file)
 '(require-final-newline (quote visit-save))
 '(ring-bell-function (quote ignore))
 '(rust-always-locate-project-on-open t)
 '(rust-indent-method-chain t)
 '(rust-indent-offset 2)
 '(save-interprogram-paste-before-kill t)
 '(save-place-file emacs-places-file)
 '(save-place-mode t)
 '(savehist-mode t)
 '(scroll-bar-mode nil)
 '(scroll-conservatively 101)
 '(select-enable-clipboard t)
 '(sh-basic-offset 2)
 '(sh-indentation 2)
 '(show-trailing-whitespace nil)
 '(standard-indent 2)
 '(tool-bar-mode nil)
 '(uniquify-buffer-name-style (quote forward) nil (uniquify))
 '(url-privacy-level (quote high))
 '(url-proxy-services (quote (("no_proxy" . "127.0.0.1"))))
 '(vc-make-backup-files t)
 '(visible-bell nil)
 '(warning-minimum-level :error)
 '(wdired-use-dired-vertical-movement (quote sometimes))
 '(whitespace-action (quote (cleanup)))
 '(whitespace-style
   (quote
    (face tabs lines-tail trailing space-before-tab indentation empty space-after-tab))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(lsp-ui-sideline-code-action ((t (:foreground "blue")))))
